### PR TITLE
Use repoOwner if no other publisher identification

### PR DESCRIPTION
**Pull request by jkisk**
Addresses error in community package updates in registry.

### CODE REVIEW

**Comment by stack72** [comment]
I'm not sure what error this is addressing - please can you link it?

**Comment by jkisk** [comment]
> I'm not sure what error this is addressing - please can you link it?

Sure thing: https://github.com/pulumi/registry/runs/7117493458?check_suite_focus=true

**Comment by jkisk** [comment]
If we want to improve the display quality of the publisher name in this case of falling back to repoOwner, perhaps we could use cases.Title() as discussed here: https://gosamples.dev/uppercase-first-letter/

**Comment by jkisk** [comment]
Link to go playground so you can see how this will behave: https://go.dev/play/p/AcX81hsL589

**Review by stack72 — APPROVED** [review]

**Pull request merged**
