### PR TITLE
update pulumi dependency

### PR DESCRIPTION
**Pull request by sean1588**
this PR updates the pulumi/pkg dependency to point to the latest commit that is on master so we can get through the codegen changes made from the following PRs:

https://github.com/pulumi/pulumi/pull/11937
https://github.com/pulumi/pulumi/pull/11811

this dependency update is also being done for the resourcedocsgen tool in the docs repo: https://github.com/pulumi/docs/pull/8480

### CODE REVIEW

**Comment by zchase** [comment]
I'd vote to wait until the new version of the CLI is released. Pinning to the commit could be causing the test failures.

**Comment by sean1588** [comment]
yeah I would feel more comfortable waiting as well.

**Comment by sean1588** [comment]
@zchase, the new version of pulumi has been released so I updated the dependencies. I also updated the resourcedocsgen tool in docs as well in this [PR](https://github.com/pulumi/docs/pull/8480). I tagged you on that one as well. Should we consolidate both of these tools as they seemingly do the same thing. In the docs repo it says to use the resourcedocsgen tool to generate the api docs and in the registry it says to use the registrygen tool to do this. Is there a reason why we can't use just one of these or is there something that one does that the other does not?

cc @cnunciato

**Review by zchase — APPROVED** [review]
LGTM --- I don't have enough context to have informed opinion on the two tools. I've only encountered `registrygen` in the things I've done, not sure what `resourcedocsgen` does. But if it is the same functionality we should absolutely consolidate!

My initial concern would be the `resourcedocsgen` generates things in `/docs` that `registrygen` doesn't. Though regardless of that it'd be nice to have one tool do the generation.

**Pull request merged**
